### ISSUE TITLE
Gracefully handle v8flags failure?

### ISSUE THREAD

**Issue by brycefisher** [tkellen/js-liftoff#51]
Related to https://github.com/shipitjs/shipit/issues/70 and https://github.com/tkellen/js-v8flags/issues/13 , if `HOME` is not accessible, this can cause upstream modules that require liftoff to fail (even if they don't explicitly need any specific v8flags).

Is it possible to issue a warning and keep going if v8flags fails for some reason? The specific case I ran into today is where the uid executing the node process doesn't have access to the `$HOME` directory.

**Comment by tkellen** [comment]
Would you mind opening this issue on v8flags? This definitely needs to be addressed there. I have a few ideas for how we can resolve this!

**Comment by brycefisher** [comment]
Yeah! Thanks for positivity.
