### ISSUE TITLE
Support not having a configuration file to search for

### ISSUE THREAD

**Issue by mprobst** [tkellen/js-liftoff#52]
I have a utility that you'd run on files within a project ([angular/clang-format], a JavaScript code formatter).  I'm trying to use Liftoff to respawn my node library and use whatever `clang-format` is in the next `node_modules` folder as seen from the file being formatted.

My utility has no configuration file, so that cannot anchor the search. Should I just use plain `node-resolve`?

**Comment by tkellen** [comment]
Sorry for the slow reply @mprobst.  I do think you'd be well served by `node-resolve` for this case!

**Comment by mprobst** [comment]
Yeah, I figured so much. For the reference if someone finds this, I added that here: https://github.com/angular/clang-format/commit/2f9ceb9c3200e0ea3eeb6f8191ed28f4265ff923
